version: "3.3"

services:

  app:
    build: .
    restart: always
    environment:
      JIMMY_CONFIG: production.cfg
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./jimmy:/jimmy

  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
