version: "3.3"

services:

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build: .
    restart: always
    environment:
      JIMMY_CONFIG: production.cfg
    volumes:
      - ./jimmy:/jimmy

  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
